USE EBMS;

INSERT INTO product_review VALUES (3, 71, '4', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2022-03-15');
INSERT INTO product_review VALUES (189, 113, '2', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2022-05-31');
INSERT INTO product_review VALUES (45, 163, '5', '', '2022-04-13');
INSERT INTO product_review VALUES (78, 25, '2', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2022-05-14');
INSERT INTO product_review VALUES (68, 144, '3', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2022-03-19');
INSERT INTO product_review VALUES (35, 186, '2', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2022-04-18');
INSERT INTO product_review VALUES (130, 155, '2', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2022-05-19');
INSERT INTO product_review VALUES (27, 148, '2', 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2022-04-23');
INSERT INTO product_review VALUES (98, 151, '3', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-06-15');
INSERT INTO product_review VALUES (39, 1, '1', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2022-05-28');
INSERT INTO product_review VALUES (198, 180, '4', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2022-04-26');
INSERT INTO product_review VALUES (87, 32, '5', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2022-06-01');
INSERT INTO product_review VALUES (128, 122, '1', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2022-03-15');
INSERT INTO product_review VALUES (111, 140, '1', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2022-04-17');
INSERT INTO product_review VALUES (44, 72, '3', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-03-04');
INSERT INTO product_review VALUES (22, 81, '4', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2022-05-27');
INSERT INTO product_review VALUES (150, 90, '4', '', '2022-03-28');
INSERT INTO product_review VALUES (129, 134, '5', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2022-06-05');
INSERT INTO product_review VALUES (149, 52, '1', '', '2022-04-26');
INSERT INTO product_review VALUES (182, 176, '1', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2022-05-26');
INSERT INTO product_review VALUES (104, 156, '1', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2022-04-25');
INSERT INTO product_review VALUES (27, 177, '1', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2022-04-03');
INSERT INTO product_review VALUES (17, 111, '4', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2022-06-11');
INSERT INTO product_review VALUES (183, 112, '5', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2022-03-09');
INSERT INTO product_review VALUES (34, 21, '5', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2022-03-17');
INSERT INTO product_review VALUES (141, 153, '5', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2022-03-05');
INSERT INTO product_review VALUES (89, 122, '1', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2022-05-08');
INSERT INTO product_review VALUES (110, 95, '2', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2022-02-21');
INSERT INTO product_review VALUES (43, 35, '3', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '2022-03-05');
INSERT INTO product_review VALUES (111, 38, '3', '', '2022-05-24');
INSERT INTO product_review VALUES (151, 109, '2', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2022-05-14');
INSERT INTO product_review VALUES (163, 115, '1', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2022-05-13');
INSERT INTO product_review VALUES (44, 6, '5', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2022-05-22');
INSERT INTO product_review VALUES (9, 193, '3', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2022-05-17');
INSERT INTO product_review VALUES (2, 46, '4', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2022-02-25');
INSERT INTO product_review VALUES (138, 176, '4', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2022-05-26');
INSERT INTO product_review VALUES (31, 169, '4', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2022-06-15');
INSERT INTO product_review VALUES (121, 6, '3', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2022-02-24');
INSERT INTO product_review VALUES (151, 113, '4', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2022-05-23');
INSERT INTO product_review VALUES (107, 192, '5', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2022-04-08');
INSERT INTO product_review VALUES (26, 165, '5', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2022-05-01');
INSERT INTO product_review VALUES (20, 190, '1', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2022-03-07');
INSERT INTO product_review VALUES (31, 20, '3', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2022-03-11');
INSERT INTO product_review VALUES (127, 168, '5', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2022-06-12');
INSERT INTO product_review VALUES (150, 99, '4', '', '2022-06-05');
INSERT INTO product_review VALUES (162, 68, '3', '', '2022-04-07');
INSERT INTO product_review VALUES (184, 161, '3', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-06-04');
INSERT INTO product_review VALUES (46, 39, '2', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2022-04-19');
INSERT INTO product_review VALUES (13, 28, '4', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2022-05-02');
INSERT INTO product_review VALUES (128, 28, '5', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2022-03-15');
INSERT INTO product_review VALUES (68, 129, '5', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2022-03-19');
INSERT INTO product_review VALUES (185, 81, '3', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2022-04-21');
INSERT INTO product_review VALUES (62, 5, '4', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '2022-06-06');
INSERT INTO product_review VALUES (190, 108, '4', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2022-05-10');
INSERT INTO product_review VALUES (115, 21, '2', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2022-03-01');
INSERT INTO product_review VALUES (170, 25, '5', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2022-04-09');
INSERT INTO product_review VALUES (116, 151, '5', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2022-04-26');
INSERT INTO product_review VALUES (151, 84, '5', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2022-05-23');
INSERT INTO product_review VALUES (173, 18, '4', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2022-06-04');
INSERT INTO product_review VALUES (131, 110, '4', '', '2022-05-16');
INSERT INTO product_review VALUES (199, 122, '3', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2022-02-25');
INSERT INTO product_review VALUES (140, 96, '2', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2022-06-10');
INSERT INTO product_review VALUES (173, 10, '2', '', '2022-06-04');
INSERT INTO product_review VALUES (29, 87, '5', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2022-04-07');
INSERT INTO product_review VALUES (118, 176, '2', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-04-20');
INSERT INTO product_review VALUES (14, 39, '4', '', '2022-06-04');
INSERT INTO product_review VALUES (109, 33, '4', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2022-05-25');
INSERT INTO product_review VALUES (184, 9, '1', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2022-06-04');
INSERT INTO product_review VALUES (182, 58, '3', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2022-05-26');
INSERT INTO product_review VALUES (109, 19, '2', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2022-06-04');
INSERT INTO product_review VALUES (4, 27, '2', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2022-03-02');
INSERT INTO product_review VALUES (180, 91, '2', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2022-04-21');
INSERT INTO product_review VALUES (142, 72, '5', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2022-05-20');
INSERT INTO product_review VALUES (142, 23, '5', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2022-05-20');
INSERT INTO product_review VALUES (57, 97, '5', '', '2022-04-05');
INSERT INTO product_review VALUES (150, 137, '3', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2022-06-05');
INSERT INTO product_review VALUES (140, 185, '4', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2022-05-07');
INSERT INTO product_review VALUES (142, 116, '5', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2022-04-21');
INSERT INTO product_review VALUES (5, 86, '1', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2022-04-02');
INSERT INTO product_review VALUES (76, 186, '4', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2022-03-04');
INSERT INTO product_review VALUES (173, 62, '4', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2022-06-04');
INSERT INTO product_review VALUES (145, 131, '2', '', '2022-05-18');
INSERT INTO product_review VALUES (33, 32, '2', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2022-03-21');
INSERT INTO product_review VALUES (99, 22, '5', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2022-03-15');
INSERT INTO product_review VALUES (165, 129, '1', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-02-27');
INSERT INTO product_review VALUES (135, 149, '1', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2022-02-13');
INSERT INTO product_review VALUES (173, 80, '3', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-04-22');
INSERT INTO product_review VALUES (86, 101, '5', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2022-04-08');
INSERT INTO product_review VALUES (99, 197, '4', 'Fusce consequat. Nulla nisl. Nunc nisl.', '2022-04-03');
INSERT INTO product_review VALUES (150, 41, '3', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2022-03-28');
INSERT INTO product_review VALUES (88, 68, '4', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2022-03-19');
INSERT INTO product_review VALUES (13, 5, '5', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2022-04-21');
INSERT INTO product_review VALUES (38, 51, '3', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2022-03-30');
INSERT INTO product_review VALUES (7, 186, '2', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2022-06-03');
INSERT INTO product_review VALUES (43, 186, '2', '', '2022-03-05');
INSERT INTO product_review VALUES (140, 124, '5', 'Fusce consequat. Nulla nisl. Nunc nisl.', '2022-05-07');
INSERT INTO product_review VALUES (29, 10, '2', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2022-05-08');
INSERT INTO product_review VALUES (25, 150, '4', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2022-03-25');
INSERT INTO product_review VALUES (181, 80, '1', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2022-03-27');
INSERT INTO product_review VALUES (27, 22, '5', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2022-02-24');
INSERT INTO product_review VALUES (123, 76, '4', '', '2022-04-03');
INSERT INTO product_review VALUES (104, 174, '5', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-04-25');
INSERT INTO product_review VALUES (26, 112, '5', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2022-05-01');
INSERT INTO product_review VALUES (38, 5, '1', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2022-05-18');
INSERT INTO product_review VALUES (60, 139, '3', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2022-06-06');
INSERT INTO product_review VALUES (118, 101, '4', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2022-04-20');
INSERT INTO product_review VALUES (76, 29, '4', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2022-06-07');
INSERT INTO product_review VALUES (43, 90, '1', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2022-03-26');
INSERT INTO product_review VALUES (179, 194, '3', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2022-02-23');
INSERT INTO product_review VALUES (66, 96, '3', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-03-09');
INSERT INTO product_review VALUES (132, 113, '1', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-05-08');
INSERT INTO product_review VALUES (145, 191, '4', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2022-05-18');
INSERT INTO product_review VALUES (168, 92, '5', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2022-04-04');
INSERT INTO product_review VALUES (157, 146, '5', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2022-04-07');
INSERT INTO product_review VALUES (106, 118, '5', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2022-04-10');
INSERT INTO product_review VALUES (156, 179, '5', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2022-02-25');
INSERT INTO product_review VALUES (66, 93, '5', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2022-04-25');
INSERT INTO product_review VALUES (85, 136, '1', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2022-03-30');
INSERT INTO product_review VALUES (174, 42, '5', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-04-24');
INSERT INTO product_review VALUES (89, 103, '1', '', '2022-04-23');
INSERT INTO product_review VALUES (60, 32, '4', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2022-05-15');
INSERT INTO product_review VALUES (101, 101, '5', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2022-03-03');
INSERT INTO product_review VALUES (162, 155, '3', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2022-04-11');
INSERT INTO product_review VALUES (121, 82, '2', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2022-03-28');
INSERT INTO product_review VALUES (182, 196, '1', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2022-02-17');
INSERT INTO product_review VALUES (130, 141, '4', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2022-06-05');
INSERT INTO product_review VALUES (45, 130, '1', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2022-04-13');
INSERT INTO product_review VALUES (175, 21, '1', '', '2022-03-03');
INSERT INTO product_review VALUES (167, 97, '4', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2022-04-09');
INSERT INTO product_review VALUES (29, 136, '4', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2022-05-08');
INSERT INTO product_review VALUES (36, 22, '5', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '2022-05-14');
INSERT INTO product_review VALUES (160, 133, '1', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2022-03-13');
INSERT INTO product_review VALUES (127, 45, '3', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2022-06-12');
INSERT INTO product_review VALUES (145, 179, '1', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2022-05-24');
INSERT INTO product_review VALUES (2, 128, '2', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-02-25');
INSERT INTO product_review VALUES (12, 43, '1', '', '2022-05-27');
INSERT INTO product_review VALUES (59, 171, '1', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-06-08');
INSERT INTO product_review VALUES (131, 13, '2', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2022-04-09');
INSERT INTO product_review VALUES (33, 120, '1', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2022-03-19');
INSERT INTO product_review VALUES (13, 10, '1', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-06-10');
INSERT INTO product_review VALUES (126, 164, '2', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2022-05-28');
INSERT INTO product_review VALUES (5, 8, '5', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-04-02');
INSERT INTO product_review VALUES (38, 18, '4', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2022-03-16');
INSERT INTO product_review VALUES (151, 142, '1', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2022-05-23');
INSERT INTO product_review VALUES (32, 198, '2', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2022-05-18');
INSERT INTO product_review VALUES (30, 131, '5', '', '2022-03-02');
INSERT INTO product_review VALUES (168, 32, '5', '', '2022-02-26');
INSERT INTO product_review VALUES (132, 62, '3', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2022-05-08');
INSERT INTO product_review VALUES (52, 13, '5', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2022-04-16');
INSERT INTO product_review VALUES (187, 143, '4', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2022-03-04');
INSERT INTO product_review VALUES (107, 35, '3', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2022-04-08');
INSERT INTO product_review VALUES (115, 43, '4', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2022-03-01');
INSERT INTO product_review VALUES (35, 43, '3', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2022-04-18');
INSERT INTO product_review VALUES (41, 59, '5', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2022-04-06');
INSERT INTO product_review VALUES (67, 16, '5', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2022-04-22');
INSERT INTO product_review VALUES (93, 25, '2', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2022-04-11');
INSERT INTO product_review VALUES (179, 183, '2', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2022-02-23');
INSERT INTO product_review VALUES (37, 186, '1', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2022-02-27');
INSERT INTO product_review VALUES (26, 150, '5', 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2022-04-25');
INSERT INTO product_review VALUES (87, 162, '4', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2022-06-01');
INSERT INTO product_review VALUES (27, 167, '2', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2022-06-06');
INSERT INTO product_review VALUES (143, 13, '4', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2022-03-29');
INSERT INTO product_review VALUES (33, 181, '2', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2022-06-08');
INSERT INTO product_review VALUES (57, 33, '5', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2022-04-05');
INSERT INTO product_review VALUES (55, 88, '2', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2022-05-20');
INSERT INTO product_review VALUES (152, 97, '2', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2022-06-07');
INSERT INTO product_review VALUES (157, 50, '5', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2022-02-19');
INSERT INTO product_review VALUES (88, 41, '4', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2022-03-19');
INSERT INTO product_review VALUES (63, 6, '4', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2022-05-20');
INSERT INTO product_review VALUES (141, 157, '4', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2022-04-11');
INSERT INTO product_review VALUES (121, 192, '2', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2022-05-28');
INSERT INTO product_review VALUES (29, 76, '5', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2022-04-07');
INSERT INTO product_review VALUES (15, 107, '1', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-06-02');
INSERT INTO product_review VALUES (106, 164, '5', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2022-02-22');
INSERT INTO product_review VALUES (82, 145, '3', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2022-03-15');
INSERT INTO product_review VALUES (12, 76, '5', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2022-04-24');
INSERT INTO product_review VALUES (114, 116, '5', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2022-04-03');
INSERT INTO product_review VALUES (74, 19, '3', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2022-04-01');
INSERT INTO product_review VALUES (32, 182, '5', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2022-05-18');
INSERT INTO product_review VALUES (182, 167, '3', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2022-02-17');
INSERT INTO product_review VALUES (101, 107, '3', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2022-04-07');
INSERT INTO product_review VALUES (65, 193, '1', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2022-03-11');
INSERT INTO product_review VALUES (53, 119, '4', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2022-06-15');
INSERT INTO product_review VALUES (93, 140, '1', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2022-03-17');
INSERT INTO product_review VALUES (200, 7, '2', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2022-03-27');
INSERT INTO product_review VALUES (16, 7, '2', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2022-04-21');
INSERT INTO product_review VALUES (5, 60, '2', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2022-04-02');
INSERT INTO product_review VALUES (96, 191, '4', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2022-05-19');
INSERT INTO product_review VALUES (119, 151, '2', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2022-05-04');
INSERT INTO product_review VALUES (93, 83, '4', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-03-17');
INSERT INTO product_review VALUES (115, 194, '2', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-03-01');
INSERT INTO product_review VALUES (182, 159, '1', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2022-05-26');
INSERT INTO product_review VALUES (184, 74, '1', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2022-06-04');
INSERT INTO product_review VALUES (30, 153, '5', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2022-05-08');
INSERT INTO product_review VALUES (111, 20, '2', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2022-03-27');
INSERT INTO product_review VALUES (22, 94, '2', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '2022-05-27');
INSERT INTO product_review VALUES (2, 79, '1', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2022-02-25');
INSERT INTO product_review VALUES (53, 7, '4', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2022-06-15');
INSERT INTO product_review VALUES (115, 108, '2', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2022-05-08');
INSERT INTO product_review VALUES (27, 19, '3', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2022-04-23');
