USE EBMS;

INSERT INTO da_review VALUES (181, 145, 1, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-03-26');
INSERT INTO da_review VALUES (103, 29, 4, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2022-03-19');
INSERT INTO da_review VALUES (177, 131, 4, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-03-03');
INSERT INTO da_review VALUES (190, 83, 3, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2022-05-16');
INSERT INTO da_review VALUES (138, 166, 4, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2022-06-05');
INSERT INTO da_review VALUES (144, 79, 1, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2022-03-04');
INSERT INTO da_review VALUES (166, 83, 3, '', '2022-06-06');
INSERT INTO da_review VALUES (114, 71, 3, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2022-03-30');
INSERT INTO da_review VALUES (14, 7, 1, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2022-06-09');
INSERT INTO da_review VALUES (131, 101, 1, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2022-04-04');
INSERT INTO da_review VALUES (178, 88, 4, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-06-18');
INSERT INTO da_review VALUES (117, 39, 4, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2022-06-01');
INSERT INTO da_review VALUES (44, 72, 1, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2022-05-28');
INSERT INTO da_review VALUES (168, 11, 4, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2022-06-02');
INSERT INTO da_review VALUES (95, 173, 3, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2022-05-18');
INSERT INTO da_review VALUES (62, 96, 2, '', '2022-06-20');
INSERT INTO da_review VALUES (189, 110, 2, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-03-14');
INSERT INTO da_review VALUES (81, 8, 5, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2022-06-08');
INSERT INTO da_review VALUES (128, 10, 4, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2022-03-31');
INSERT INTO da_review VALUES (36, 114, 5, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-06-05');
INSERT INTO da_review VALUES (186, 5, 4, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2022-04-30');
INSERT INTO da_review VALUES (111, 92, 2, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2022-05-29');
INSERT INTO da_review VALUES (13, 22, 2, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2022-06-05');
INSERT INTO da_review VALUES (120, 20, 2, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2022-05-29');
INSERT INTO da_review VALUES (174, 177, 3, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2022-04-29');
INSERT INTO da_review VALUES (42, 122, 2, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2022-06-08');
INSERT INTO da_review VALUES (74, 172, 5, '', '2022-03-26');
INSERT INTO da_review VALUES (115, 34, 3, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2022-05-01');
INSERT INTO da_review VALUES (189, 59, 1, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2022-06-05');
INSERT INTO da_review VALUES (14, 108, 1, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2022-06-11');
INSERT INTO da_review VALUES (69, 160, 5, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2022-04-01');
INSERT INTO da_review VALUES (1, 16, 5, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2022-05-16');
INSERT INTO da_review VALUES (13, 10, 4, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2022-05-08');
INSERT INTO da_review VALUES (40, 12, 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2022-06-06');
INSERT INTO da_review VALUES (149, 56, 3, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2022-05-06');
INSERT INTO da_review VALUES (41, 28, 2, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2022-04-12');
INSERT INTO da_review VALUES (106, 78, 1, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2022-03-11');
INSERT INTO da_review VALUES (89, 66, 1, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-04-16');
INSERT INTO da_review VALUES (115, 157, 3, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2022-03-07');
INSERT INTO da_review VALUES (99, 187, 5, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2022-04-20');
INSERT INTO da_review VALUES (187, 47, 4, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2022-03-14');
INSERT INTO da_review VALUES (63, 70, 2, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2022-03-09');
INSERT INTO da_review VALUES (43, 116, 5, '', '2022-04-05');
INSERT INTO da_review VALUES (58, 107, 3, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2022-04-14');
INSERT INTO da_review VALUES (143, 88, 1, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-05-10');
INSERT INTO da_review VALUES (9, 145, 1, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2022-05-24');
INSERT INTO da_review VALUES (164, 174, 2, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2022-04-07');
INSERT INTO da_review VALUES (77, 97, 4, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2022-05-23');
INSERT INTO da_review VALUES (31, 28, 1, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2022-06-22');
INSERT INTO da_review VALUES (74, 130, 2, '', '2022-06-05');
INSERT INTO da_review VALUES (137, 132, 3, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2022-03-12');
INSERT INTO da_review VALUES (181, 169, 3, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2022-04-06');
INSERT INTO da_review VALUES (90, 58, 1, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-03-24');
INSERT INTO da_review VALUES (196, 154, 5, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2022-05-31');
INSERT INTO da_review VALUES (69, 13, 5, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2022-06-04');
INSERT INTO da_review VALUES (175, 23, 3, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2022-03-15');
INSERT INTO da_review VALUES (57, 123, 5, '', '2022-05-08');
INSERT INTO da_review VALUES (27, 142, 5, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2022-04-15');
INSERT INTO da_review VALUES (165, 167, 1, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2022-03-11');
INSERT INTO da_review VALUES (109, 157, 1, '', '2022-04-11');
INSERT INTO da_review VALUES (2, 80, 2, '', '2022-03-06');
INSERT INTO da_review VALUES (100, 42, 1, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2022-05-13');
INSERT INTO da_review VALUES (148, 181, 5, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2022-03-29');
INSERT INTO da_review VALUES (153, 84, 5, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-04-24');
INSERT INTO da_review VALUES (120, 94, 3, '', '2022-04-03');
INSERT INTO da_review VALUES (41, 88, 1, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2022-06-14');
INSERT INTO da_review VALUES (131, 138, 1, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2022-05-06');
INSERT INTO da_review VALUES (35, 95, 4, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2022-02-26');
INSERT INTO da_review VALUES (30, 2, 4, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2022-03-08');
INSERT INTO da_review VALUES (138, 17, 5, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2022-03-22');
INSERT INTO da_review VALUES (52, 157, 4, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2022-04-23');
INSERT INTO da_review VALUES (111, 163, 4, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2022-04-03');
INSERT INTO da_review VALUES (6, 3, 3, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2022-04-23');
INSERT INTO da_review VALUES (88, 174, 5, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2022-03-26');
INSERT INTO da_review VALUES (176, 115, 5, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2022-06-17');
INSERT INTO da_review VALUES (120, 48, 2, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2022-04-15');
INSERT INTO da_review VALUES (37, 3, 1, 'Fusce consequat. Nulla nisl. Nunc nisl.', '2022-03-11');
INSERT INTO da_review VALUES (110, 4, 1, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2022-02-28');
INSERT INTO da_review VALUES (156, 172, 4, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2022-04-01');
INSERT INTO da_review VALUES (90, 169, 3, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2022-05-17');
INSERT INTO da_review VALUES (45, 37, 3, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2022-05-25');
INSERT INTO da_review VALUES (52, 76, 5, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2022-03-09');
INSERT INTO da_review VALUES (43, 45, 4, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2022-03-23');
INSERT INTO da_review VALUES (134, 81, 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2022-03-22');
INSERT INTO da_review VALUES (162, 167, 4, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2022-04-13');
INSERT INTO da_review VALUES (13, 132, 3, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2022-04-27');
INSERT INTO da_review VALUES (124, 168, 5, '', '2022-05-18');
INSERT INTO da_review VALUES (78, 55, 2, '', '2022-05-23');
INSERT INTO da_review VALUES (15, 80, 4, 'Fusce consequat. Nulla nisl. Nunc nisl.', '2022-06-25');
INSERT INTO da_review VALUES (172, 109, 2, '', '2022-05-21');
INSERT INTO da_review VALUES (41, 56, 5, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2022-05-20');
INSERT INTO da_review VALUES (34, 89, 2, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2022-04-12');
INSERT INTO da_review VALUES (37, 16, 5, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2022-03-11');
INSERT INTO da_review VALUES (1, 133, 2, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2022-05-09');
INSERT INTO da_review VALUES (153, 132, 5, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2022-03-10');
INSERT INTO da_review VALUES (174, 158, 3, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2022-05-01');
INSERT INTO da_review VALUES (199, 36, 5, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-03-12');
INSERT INTO da_review VALUES (173, 143, 3, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-06-14');
INSERT INTO da_review VALUES (88, 11, 5, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2022-03-18');
INSERT INTO da_review VALUES (130, 64, 5, '', '2022-05-30');
INSERT INTO da_review VALUES (145, 125, 5, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2022-05-27');
INSERT INTO da_review VALUES (161, 190, 3, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2022-05-14');
INSERT INTO da_review VALUES (101, 156, 3, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2022-04-18');
INSERT INTO da_review VALUES (33, 118, 2, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '2022-04-02');
INSERT INTO da_review VALUES (103, 121, 4, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2022-05-15');
INSERT INTO da_review VALUES (91, 129, 5, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2022-06-06');
INSERT INTO da_review VALUES (60, 94, 4, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '2022-05-26');
INSERT INTO da_review VALUES (32, 72, 4, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2022-06-21');
INSERT INTO da_review VALUES (78, 144, 2, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2022-06-06');
INSERT INTO da_review VALUES (7, 57, 5, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2022-05-28');
INSERT INTO da_review VALUES (53, 13, 3, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2022-06-22');
INSERT INTO da_review VALUES (124, 165, 5, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2022-04-21');
INSERT INTO da_review VALUES (32, 2, 2, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2022-05-29');
INSERT INTO da_review VALUES (170, 98, 1, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2022-04-22');
INSERT INTO da_review VALUES (184, 180, 5, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2022-03-13');
INSERT INTO da_review VALUES (8, 122, 2, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2022-07-02');
INSERT INTO da_review VALUES (75, 28, 3, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2022-03-31');
INSERT INTO da_review VALUES (172, 7, 3, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2022-06-19');
INSERT INTO da_review VALUES (25, 154, 2, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2022-04-02');
INSERT INTO da_review VALUES (7, 125, 3, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2022-05-30');
INSERT INTO da_review VALUES (78, 88, 2, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2022-04-25');
INSERT INTO da_review VALUES (104, 184, 1, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2022-05-07');
INSERT INTO da_review VALUES (121, 145, 5, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-06-14');
INSERT INTO da_review VALUES (101, 79, 2, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2022-06-08');
INSERT INTO da_review VALUES (152, 125, 4, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-06-19');
INSERT INTO da_review VALUES (26, 96, 5, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-05-10');
INSERT INTO da_review VALUES (62, 102, 1, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2022-06-23');
INSERT INTO da_review VALUES (138, 103, 4, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2022-04-09');
INSERT INTO da_review VALUES (27, 124, 4, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2022-03-07');
INSERT INTO da_review VALUES (24, 113, 4, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2022-05-30');
INSERT INTO da_review VALUES (60, 44, 4, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2022-03-23');
INSERT INTO da_review VALUES (193, 10, 4, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2022-05-07');
INSERT INTO da_review VALUES (168, 179, 4, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2022-06-12');
INSERT INTO da_review VALUES (99, 63, 3, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2022-04-17');
INSERT INTO da_review VALUES (102, 133, 3, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2022-03-16');
INSERT INTO da_review VALUES (151, 195, 4, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2022-05-19');
INSERT INTO da_review VALUES (189, 30, 1, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2022-05-30');
INSERT INTO da_review VALUES (197, 92, 5, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2022-06-22');
INSERT INTO da_review VALUES (126, 113, 2, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2022-05-22');
INSERT INTO da_review VALUES (135, 34, 3, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2022-06-24');
INSERT INTO da_review VALUES (79, 69, 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2022-06-15');
INSERT INTO da_review VALUES (107, 161, 2, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2022-05-31');
INSERT INTO da_review VALUES (60, 98, 1, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2022-06-13');
INSERT INTO da_review VALUES (87, 102, 5, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2022-06-11');
INSERT INTO da_review VALUES (156, 83, 1, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2022-06-22');
INSERT INTO da_review VALUES (168, 85, 3, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2022-04-17');
INSERT INTO da_review VALUES (31, 30, 5, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2022-06-26');
INSERT INTO da_review VALUES (101, 181, 1, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2022-03-12');
INSERT INTO da_review VALUES (3, 39, 4, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2022-03-29');
INSERT INTO da_review VALUES (128, 47, 4, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2022-06-03');
INSERT INTO da_review VALUES (85, 9, 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2022-04-13');
INSERT INTO da_review VALUES (174, 152, 4, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2022-05-02');
INSERT INTO da_review VALUES (38, 175, 5, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2022-03-21');
INSERT INTO da_review VALUES (106, 166, 5, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2022-04-15');
INSERT INTO da_review VALUES (163, 21, 4, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2022-06-19');
INSERT INTO da_review VALUES (143, 139, 4, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-02-23');
INSERT INTO da_review VALUES (26, 83, 2, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-04-08');
INSERT INTO da_review VALUES (143, 15, 5, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2022-04-12');
INSERT INTO da_review VALUES (128, 100, 5, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2022-03-02');
INSERT INTO da_review VALUES (3, 45, 1, '', '2022-03-17');
INSERT INTO da_review VALUES (152, 158, 5, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2022-05-23');
INSERT INTO da_review VALUES (66, 6, 4, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-03-15');
INSERT INTO da_review VALUES (115, 60, 3, '', '2022-05-27');
INSERT INTO da_review VALUES (163, 125, 2, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2022-05-20');
INSERT INTO da_review VALUES (167, 172, 4, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2022-05-12');
INSERT INTO da_review VALUES (122, 151, 4, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2022-04-09');
INSERT INTO da_review VALUES (78, 104, 4, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2022-03-03');
INSERT INTO da_review VALUES (148, 88, 4, '', '2022-06-18');
INSERT INTO da_review VALUES (34, 114, 1, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2022-06-11');
INSERT INTO da_review VALUES (3, 121, 3, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2022-03-25');
INSERT INTO da_review VALUES (72, 9, 3, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2022-06-18');
INSERT INTO da_review VALUES (12, 127, 5, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2022-05-09');
INSERT INTO da_review VALUES (98, 95, 5, '', '2022-06-25');
INSERT INTO da_review VALUES (87, 184, 4, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2022-04-02');
INSERT INTO da_review VALUES (9, 97, 4, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2022-05-15');
INSERT INTO da_review VALUES (151, 91, 1, 'Fusce consequat. Nulla nisl. Nunc nisl.', '2022-06-04');
INSERT INTO da_review VALUES (183, 18, 2, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2022-04-13');
INSERT INTO da_review VALUES (88, 16, 5, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2022-03-28');
INSERT INTO da_review VALUES (82, 145, 3, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-03-28');
INSERT INTO da_review VALUES (99, 162, 5, 'Fusce consequat. Nulla nisl. Nunc nisl.', '2022-03-29');
INSERT INTO da_review VALUES (31, 19, 5, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2022-03-19');
INSERT INTO da_review VALUES (194, 125, 2, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2022-05-18');
INSERT INTO da_review VALUES (45, 111, 2, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-03-25');
INSERT INTO da_review VALUES (129, 68, 4, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-06-17');
INSERT INTO da_review VALUES (141, 150, 3, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2022-03-13');
INSERT INTO da_review VALUES (39, 37, 1, '', '2022-06-10');
INSERT INTO da_review VALUES (181, 104, 3, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2022-06-14');
INSERT INTO da_review VALUES (89, 193, 2, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2022-05-05');
INSERT INTO da_review VALUES (126, 14, 5, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2022-03-15');
INSERT INTO da_review VALUES (92, 4, 5, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2022-03-19');
INSERT INTO da_review VALUES (66, 67, 5, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2022-05-20');
INSERT INTO da_review VALUES (55, 136, 3, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2022-05-13');
INSERT INTO da_review VALUES (116, 153, 3, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2022-06-13');
INSERT INTO da_review VALUES (71, 175, 2, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2022-05-22');
INSERT INTO da_review VALUES (23, 149, 5, '', '2022-04-17');
INSERT INTO da_review VALUES (178, 28, 4, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2022-05-20');
INSERT INTO da_review VALUES (178, 58, 5, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2022-03-08');
INSERT INTO da_review VALUES (22, 125, 1, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2022-06-08');
INSERT INTO da_review VALUES (165, 117, 1, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2022-03-19');
INSERT INTO da_review VALUES (28, 68, 4, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-03-07');
